DeepDirect/deepwebide-fe

- package.json
- pnpm-lock.yaml
잘못 설치된 라우터 패키지 삭제를 깜빡해서 빠르게 삭제만 했습니다.
삭제만 한거라 별도로 이슈를 생성하진 않았습니다. 감사합니다.
> [fix] 잘못 설치된 라우터 패키지 삭제

- src/pages/LandingPage.scss
- 안경 위치 수정
- 땡스 투 소뎅님...! 감사합니다
- 반응형 수정
- 여기에서도 안경 위치가 살짝 안 맞아서 사이즈와 위치 조정했습니다
- 커서 색상 수정
- 커서 색상이 흐릿해보인다고 말씀하셔서 조금 진하게 바꿔보았는데 어떤가요~?
---
---
- Closes #39
> [Fix] 랜딩 페이지 UI 수정

- pnpm-lock.yaml
- src/App.tsx
- src/layouts/AuthLayout/AuthLayout.module.scss
- src/layouts/AuthLayout/AuthLayout.tsx
- src/main.tsx
- src/pages/SignInPage/SignInPage.tsx
- src/pages/SignUpPage/SignUpPage.tsx
- src/router/root.tsx
- src/router/routeTree.ts
- src/router/router.ts
- src/router/routes/auth/auth-layout.tsx
- src/router/routes/auth/sign-in.tsx
- src/router/routes/auth/sign-up.tsx
[Feature] 전체 라우트 설정 
---
전체적인 기반이 될 라우트 설정을 했습니다.
추가로 라우터를 연결하실때, 추가 작성해주시면 됩니다!
라우터 연결하실 때, 텐스택 라우터를 처음 사용하시는 분들을 위해 밑에 예시를 작성해두겠습니다.
라우터 컨벤션은 노션에 작성되어 있으니 참고 바랍니다!
(근데 저도 처음 써서 틀렸을수도 있으니, 이상이 있으면 연락주세요.!)
```
// routeTree.ts 작성 예시니까 너무 중요하게 보진 말기-
import { rootRoute } from './root'
// Auth 그룹
import { authLayoutRoute } from './routes/Auth/auth-layout'
import { signInRoute } from './routes/Auth/signin'
import { signUpRoute } from './routes/Auth/signup'
// Main 그룹
import { mainLayoutRoute } from './routes/main/main-layout'
import { mainRoute } from './routes/main/main'
export const routeTree = rootRoute.addChildren([
authLayoutRoute.addChildren([
loginRoute,
signUpRoute,
]),
mainLayoutRoute.addChildren([
mainRoute,
]),
])
```
---
---
Related to #34
> [Feature] 전체 라우트 설정 / DP-30

- src/components/atoms/Button/Button.scss
- src/components/molecules/FormField.module.scss
- src/components/molecules/FormField.tsx
- src/pages/SignInPage/SignInForm.tsx
- src/pages/SignInPage/SignInPage.module.scss
- src/pages/SignInPage/SignInPage.tsx
- src/pages/SignUpPage/SignUpForm.tsx
- src/pages/SignUpPage/SignUpPage.module.scss
- src/pages/SignUpPage/SignUpPage.tsx
- src/schemas/auth.schema.ts
- 회원가입 페이지 제작
- 버튼 비활성화 시 커서 또한 비활성화 표시
- 모든 필드 입력 시 버튼 활성화 처리 (인척 이메일과 인증 코드만 완료되면 되지롱-)
- 로그인 페이지 또한 버튼 비/활성화 처리
- 추가 변경 사항
- formField를 따로 제작하여, label + input + 오류 메세지를 묶어 하나의 입력 필드로 구성
- 공통 필드 스키마를 변수로 분리하여 재사용성을 높임
---
---
Closes #35
- 뭔가를 제작을 빠트린거 같은디,, 그게 뭔지 모르겠어오.. 없으면 말고,,~
> [Feature] 회원가입 페이지 UI 제작 / DP-31 

- pnpm-lock.yaml
- src/pages/SignUpPage/SignUpCompletePage.module.scss
- src/pages/SignUpPage/SignUpCompletePage.tsx
- src/pages/SignUpPage/SignUpForm.tsx
- src/router/routeTree.ts
- src/router/routes/auth/sign-up-complete.tsx
- 원용님의 제보를 통해 놓치고 있던 회원가입 완료 페이지 제작을 급하게 진행하였습니다..(압도적 감사,,
----
- 회원가입을 완료하고 나서, 회원가입 버튼을 누르면, 회원가입 완료 페이지로 이동합니다.
- 회원가입 완료 안내 페이지에서 로그인으로 버튼을 누르면 로그인 화면으로 이동합니다.
- 아직 회원가입 완료 페이지는 막아두지 않아, 그냥 링크로도 접근 가능합니다. (추후 작업 예정
---
---
Closes #60
---
- 급하게 제작해서 놓친 부분이 있을 수도 있습니다.! 있다면 말해주시면 감사하겠습니닷,,!
> [Feature] 회원가입 완료 안내 페이지 제작

- src/assets/icons/arrow-down-box.svg
- src/assets/icons/copy.svg
- src/assets/icons/edit-box.svg
- src/assets/icons/forward.svg
- src/assets/icons/mail-off.svg
- src/assets/icons/track-changes.svg
- src/assets/icons/trash.svg
- src/assets/icons/user-minus.svg
- src/components/molecules/InputMenuItem/InputMenuItem.module.scss
- src/components/molecules/InputMenuItem/InputMenuItem.tsx
- src/components/molecules/MenuItem/MenuItem.module.scss
- src/components/molecules/MenuItem/MenuItem.tsx
- src/components/molecules/ToggleInputMenuItem/ToggleInputMenuItem.module.scss
- src/components/molecules/ToggleInputMenuItem/ToggleInputMenuItem.tsx
- src/components/organisms/Modals/MeatballModal/MeatballModal.module.scss
- src/components/organisms/Modals/MeatballModal/MeatballModal.tsx
- src/features/Modals/PrivateRepoMeatballModal/PrivateRepoMeatballModal.tsx
- src/features/Modals/SharedByMeRepoMeatballModal/SharedByMeRepoMeatballModal.tsx
- src/features/Modals/SharedWithMeRepoMeatballModal/SharedWithMeRepoMeatballModal.tsx
- src/styles/_mixins.scss
Feature/dp 54/meatball modal
---
- 메인페이지의 미트볼 모달을 생성하였습니다. 
---
---
- Closes #56 
---
- 빛나는 모달 스타일 추후 수정 예정입니다.
- 다크모드 적용도 추후 시간 여유가 날 경우 진행하겠습니다.
> Feature/dp 54/meatball modal

- src/assets/icons/logout.svg
- src/components/Header/variants/UserProfile.tsx
- src/components/molecules/ProfileDropdown/ProfileDropdown.module.scss
- src/components/molecules/ProfileDropdown/ProfileDropdown.tsx
- Feature/dp 68/header modal
---
- 헤더 프로필을 눌렀을 때 나오는 로그아웃 드롭다운 제작
---
---
- Closes #68 
---
- 추후 로그아웃 API의 연결이 필요합니당
> Feature/dp 68/header modal

- src/pages/Repo/RepoPage.module.scss
- src/pages/Repo/RepoPage.tsx
hotfix(RepoPage): RepoPage 병합 충돌 해결 / DP-113
---
- 병합 충돌 해결
---
---
> hotfix(RepoPage): RepoPage 병합 충돌 해결 / DP-113

- src/api/api.ts
- src/api/client.ts
- src/main.tsx
[Feature] api.ts 생성
---
- axios 설정 추가
---
---
Closes #102 
---
환경변수로 `VITE_BASE_URL` 필요합니다.
> [Feature] api.ts 생성

- src/components/organisms/CodeEditor/MonacoCollaborativeEditor.module.scss
- src/hooks/useMonacoEditor.ts
- src/pages/Repo/RepoPage.module.scss
- src/stores/themeStore.ts
- src/styles/index.scss
다크모드가 바로 반영이 되지 않는 것을 수정하였습니다.
일부분 다크 모드를 설정하지 않았던 곳들을 설정해두었습니다.
---
---
Related to #120 
---
에디터 로딩 중 창도 그 픽맨으로 바꿀까오?
> [Fix]  다크모드 반영 수정 / DP-136

- src/components/organisms/CursorOverlay/CursorOverlay.tsx
- src/hooks/useMonacoEditor.ts
- src/hooks/useYjsCollaboration.ts
- src/stores/collaborationStore.ts
- src/types/collaboration.types.ts
- src/types/yjs.types.ts
yjs 타입 중복을 방지하기  위해, yjs.types.ts 파일을 생성하였습니다..
전체적으로 정리 좀 하면서 안전한 메서드 호출을 위한 헬퍼 함수 같은  설정이라던지,, 안전성을 위한 코드들을 넣으니 양이 많아진건 기분탓이 맞을 겁니다..
추후 rerefactoring 하겟음니다..
---
---
Related to #120 
예시:
- Closes #이슈번호
- Related to #이슈번호
---
추후 다시 수정하기는 해야하지만, 커서와 함께 이름이 뜨게 설정해보앗읍니다..
커서 색이 모두 똑같아서 다시 고쳐야하는 건 안비밇..~
> [Refactor]코드 리펙토링 / dp 136

- src/layouts/RepoLayout/RepoLayout.tsx
- src/stores/themeStore.ts
- [FE][Fix] 다크모드 최적화
---
- 다크모드 테마 로컬 스토리지가 repo 페이지 안에서만 활성화 되도록 수정
---
---
예시:
- Closes #130 
---
> fix(themeStore.ts): 다크모드 최적화 진행 / DP-147

- src/features/Repo/fileTree/FileTree.module.scss
- src/features/Repo/fileTree/FileTree.tsx
- src/features/Repo/fileTree/components/FileTreeItem/FileTreeItem.module.scss
- src/features/Repo/fileTree/components/FileTreeItem/FileTreeItem.tsx
- src/features/Repo/fileTree/hooks/useFileTreeDragDrop.ts
- src/features/Repo/fileTree/hooks/useFileTreeOperations.ts
- src/features/Repo/fileTree/types.ts
- [FE][Feature] 파일 트리 섹션 작업 2
- 파일 트리 내 드래그엔 드롭 파일 이동 기능 구현
---
- 파일 트리 내 드래그엔 드롭으로 파일 이동이 가능하게 제작하였습니다.
---
---
- Related to #128 
---
> Feature/dp 143/file tree section 2

- src/components/organisms/CodeEditor/MonacoCollaborativeEditor.tsx
- src/features/Repo/fileTree/FileTree.tsx
- src/features/Repo/fileTree/hooks/useFileTreeActions.ts
- src/hooks/repo/useFileContent.ts
- src/hooks/repo/useFileContentLoader.ts
- src/hooks/repo/useRepositoryInfo.ts
- src/hooks/repo/useYjsCollaboration.ts
- src/pages/Repo/RepoPage.tsx
- 코드 에디터에 파일이 열리게 api 연결 및 수정하였습니다.
- 협업 모드의 경우, 파일이 날라가는 오류가 있어서 수정했습니다.
---
---
Closes #153 
---
- 파일 내용이 잘 불러와지는지 확인해쥬세영
> [Feature]  코드 에디터 파일 api 연동 / DP-162

- src/features/Repo/fileTree/FileTree.tsx
- src/features/Repo/fileTree/hooks/useFileTree.ts
- src/features/Repo/fileTree/hooks/useFileTreeApi.ts
- src/features/Repo/fileTree/hooks/useFileTreeOperations.ts
- src/hooks/repo/useYjsFileTree.ts
- [Feature] 파일트리 YJS로 동기화 기능 구현
---
- A사용자가 백엔드 서버로 API요청을 보내면 그 결과가 B사용자에게로 YJS로 동기화됨
---
---
- Closes #156 
---
- 아직 큰 산 남았다..영차..
> feat(yjs): 파일 트리 yjs로 동기화 기능 구현 / DP-164

- src/pages/Main/SharedWithMeRepoPage/SharedWithMeRepoPage.tsx
[FE][Fix] 페이징 처리 수정
---
`보여지는 최대 개수(maxVisiblePages)`를 `총 개수(total)`로 잘못 입력된 것 확인하여 수정함.
---
---
Closes #158
---
> [FE][Fix] 페이징 처리 수정

- src/features/Toast/Toast.module.scss
- src/features/Toast/Toast.tsx
[Fix] theme에 따라 토스트 색상 변경
---
- theme에 따라 배경색 변경
- 배경은 light일 때 $white-1, dark일 때 $black-2로 됨
- 왼쪽 사이드 색상은 theme과 관계없이 타입별로 색상 고정됨
---
---
Closes #160
---
- default type
- success type
- error
- warning
- info
> [Fix] theme에 따라 토스트 색상 변경

- src/components/organisms/Header/RepoHeader/RepoHeader.module.scss
- src/components/organisms/Header/RepoHeader/RepoHeader.tsx
- src/components/organisms/Header/UserProfile/UserProfile.module.scss
- src/components/organisms/Header/UserProfile/UserProfile.tsx
- src/layouts/RepoLayout/RepoLayout.tsx
- [FE][Feature] chat 버튼 레포별 구분 및 활성화 시 스타일 적용
---
- chat 버튼 레포별 구분
- chat sections 활성화 시 스타일 적용
---
---
- Closes #175 
---
- chat 버튼 개인 레포에서는 안보이게 설정
- 채팅창 활성화일 때 사이드바 버튼과 동일한 활성화 스타일 적용
> Feature/dp 186/chat button

- src/components/organisms/Header/PathArea/PathArea.tsx
- src/features/Repo/fileTree/components/CreateFileModal/CreateFileModal.tsx
- src/features/Repo/fileTree/hooks/useFileTreeOperations.ts
- src/features/Repo/savePoint/SaveModal/SaveModal.tsx
- src/features/Repo/savePoint/SavePoint.tsx
- src/features/Toast/Toast.module.scss
- src/hooks/auth/useSignIn.ts
- src/hooks/auth/useSignOut.ts
- src/pages/Main/PrivateRepoPage/PrivateRepoPage.tsx
- src/pages/Main/SharedByMeRepoPage/SharedByMeRepoPage.tsx
- src/pages/Main/SharedWithMeRepoPage/SharedWithMeRepoPage.tsx
- [FE][Feature] 토스트 연결
---
- 파일 전역 토스트 작업 진행
---
---
- Closes  #186
---
- 토스트 이상 없는지 각자 확인 부탁드립니당
- 누락된 곳이 있다면.. 부탁드려용..
> Refactor/dp 192/apply toast

- src/features/Auth/SignInForm/SignInForm.tsx
- src/pages/LandingPage/LandingPage.tsx
- tsconfig.app.json
- tsconfig.node.json
- [Fix] 랜딩페이지 이미지 경로 수정
---
- import 문 추가: 각 이미지 파일을 변수로 import
- src 속성 변경: 문자열 경로를 import한 변수로 교체
---
---
- Closes #189 
- Related to #114 
---
> Fix/dp 193/deploy settings

- pnpm-lock.yaml
- src/api/fileContent.ts
- src/components/organisms/CodeEditor/MonacoCollaborativeEditor.module.scss
- src/components/organisms/CodeEditor/MonacoCollaborativeEditor.tsx
- src/components/organisms/CursorOverlay/CursorOverlay.tsx
- src/features/Repo/fileTree/FileTree.tsx
- src/features/Repo/fileTree/helpers.ts
- src/features/Repo/fileTree/hooks/useFileTreeActions.ts
- src/features/Repo/fileTree/hooks/useFileTreeApi.ts
- src/features/Repo/fileTree/hooks/useFileTreeOperations.ts
- src/features/Repo/fileTree/types.ts
- src/hooks/repo/useFileContent.ts
- src/hooks/repo/useFileContentLoader.ts
- src/hooks/repo/useFileSave.ts
- src/hooks/repo/useMonacoEditor.ts
- src/hooks/repo/useYjsCollaboration.ts
- src/hooks/repo/useYjsFileTree.ts
- src/hooks/repo/useYjsSavePoint.ts
- src/main.tsx
- src/pages/Repo/RepoPage.tsx
- src/stores/collaborationStore.ts
- src/stores/tabStore.ts
- src/stores/themeStore.ts
- src/types/repo/repo.types.ts
- src/types/repo/tabStore.types.ts
- src/types/repo/yjs.types.ts
- 실시간 저장 api 연동 및 파일트리와 모나코와 어쩌구의 협업을 위한 yjs 연동을 진행하였습니다.
- 커서 색 다르게 보이구용 이쁩니당 👍
---
---
Closes #162 
---
- 현재 탭에 잔잔바리한 오류가 남아잇으니, 그것은 신경쓰지 마시고 확인 부탁드립니닷!
> [Feature] 실시간 저장 api 연동 / DP-167

- src/features/Repo/fileTree/FileTree.tsx
- src/hooks/repo/useYjsCollaboration.ts
- 협업 모드에서 자동 저장의 탭 스타일을 수정하였습니다.
- 파일트리 전체에서 우클릭이 가능하게 수정하였습니다.
---
---
Related to #199
> [Feature] 에디터 저장 기능 및 파일 트리 수정 / DP-202

- src/components/molecules/GitHubLoginButton/GitHubLoginButton.tsx
[Fix] 소셜 로그인 안 됨
---
- origin url 비교문에 localhost로 비교하는 것때문에 발생함.
- 해당 코드 제거
---
---
Closes #206
---
쓸데 없는 코드를 추가해버려서 죄송합니다ㅠㅠㅠㅠㅠ
> [Fix] 소셜 로그인 안 됨

- src/components/organisms/InvitationLinkForm/InvitationLinkForm.tsx
이미지 사용 방식 import로 수정
---
---
`Closes #이슈번호` 또는 `Related to #이슈번호` 형태로 작성
- Closes #212
> [Fix] 입장 코드 입력 페이지 lock icon 이미지 import

- src/hooks/repo/useFileContentLoader.ts
- 빈 파일을 클릭시 무한 로딩이 되어 화면이 먹통이 되어서 수정해보았슴니닷
---
> fix(editor): 무한 로딩 방지용  코드 수정 / DP-204
